
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soal-jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: student-13
    name: in-cluster
  syncPolicy:
    automated: {}
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: https://github.com/sofusalbertsen/super-octo-fishstick
      targetRevision: main
      ref: values
